
DROP DATABASE IF EXISTS `user`;
CREATE DATABASE `user` DEFAULT CHARACTER SET utf8mb4;
USE user;


DROP TABLE IF EXISTS account;
CREATE TABLE account(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

INSERT INTO account(username, password) VALUES('Kylie','706818');
SELECT * FROM account;


-- DROP TABLE IF EXISTS profile;
CREATE TABLE profile(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	first VARCHAR(50) NOT NULL,
    last VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    dob VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE ppp(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT
);
